### DISCUSSION TITLE
[WISH] VPN Client with multiple VPN providers - GLUETUN

### DISCUSSION THREAD

**Discussion by zunami** [swizzin/swizzin#950] [Feature Requests] [answered]
hello i could not find where to post feature requests. i hope i'm in the right place.

I would like to have a **VPN client** for swizzin.
There is for docker the [gluetun VPN client](https://github.com/qdm12/gluetun)
_Advantages:_
- multiple VPN providers
- using OpenVPN or Wireguard, DNS over TLS
- with a few proxy servers built-in

I read that you can set it up to run the external connections over VPN and you can still reach the **internal traffic over the LAN**.

[https://github.com/qdm12/gluetun](https://github.com/qdm12/gluetun)

**Comment by brettpetch** [comment, marked as answer]
Hi, We don't run containers as part of our project scope. Users have always been able to do this themselves. Here's an example of the vpn container with qBit & a socks5 proxy.

```yml
version: "3"
services:
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent:legacy
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/qbittorrent/config/:/config
      - /home/user/storage/:/home/user/storage
    network_mode: "service:gluetun"
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 127.0.0.1:8888:8888/tcp # HTTP proxy
      - 127.0.0.1:8388:8388/tcp # Shadowsocks
      - 127.0.0.1:8388:8388/udp # Shadowsocks
      - 127.0.0.1:1080:1080 #socks5 proxy
      - 127.0.0.1:8080:8080 # qBittorrent WebUI
    volumes:
      - /opt/gluetun/config:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=
      - SERVER_CITIES=
      - FIREWALL_VPN_INPUT_PORTS=
      - TZ=Etc/UTC
      - HTTPPROXY=on
      - DOT=on
      - DOT_PROVIDERS=cloudflare
      - DOT_CACHING=off
      - BLOCK_MALICIOUS=off
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
      - DNS_ADDRESS=1.1.1.1
  socks5:
    image: serjs/go-socks5-proxy
    depends_on:
      - gluetun
    environment:
      - PROXY_USER=
      - PROXY_PASSWORD=
      - PROXY_PORT=1080
    network_mode: "service:gluetun"
```
